apiVersion: v1
kind: Secret
metadata:
  name: backend-employee-db-secret
type: Opaque
stringData:
  username: {{ .Values.backend.env.datasourceUsername | quote }}
  password: {{ .Values.backend.env.datasourcePassword | quote }}
