#
apiVersion: v1
kind: Service
metadata:
  name: backend-employee
spec:
  selector:
    app: backend-employee
  ports:
    - port: {{ .Values.backend.service.port }}
      targetPort: 8080
  type: ClusterIP
