#
apiVersion: v1
kind: Secret
metadata:
  name: backend-employee-db-secret
type: Opaque
stringData:
  username: {{ .Values.postgres.username | quote }}
  password: {{ .Values.postgres.password | quote }}
