#
apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend-employee
spec:
  replicas: {{ .Values.frontend.replicaCount }}
  selector:
    matchLabels:
      app: frontend-employee
  template:
    metadata:
      labels:
        app: frontend-employee
    spec:
      containers:
        - name: frontend-employee
          image: "{{ .Values.frontend.image.repository }}:{{ .Values.frontend.image.tag }}"
          imagePullPolicy: {{ .Values.frontend.image.pullPolicy }}
          ports:
            - containerPort: 3000
          env:
            - name: BACKEND_URL
              value: {{ .Values.frontend.env.backendUrl | quote }}
          readinessProbe:
            httpGet:
              path: /health
              port: 3000
          livenessProbe:
            httpGet:
              path: /health
              port: 3000
            initialDelaySeconds: 10
#
