apiVersion: v1
kind: Service
metadata:
  name: postgres
spec:
  ports:
    - port: {{ .Values.postgres.port }}
      targetPort: {{ .Values.postgres.port }}
---
apiVersion: v1
kind: Endpoints
metadata:
  name: postgres
subsets:
  - addresses:
      - ip: {{ .Values.postgres.externalIp }}
    ports:
      - port: {{ .Values.postgres.port }}
